# Generated by Django 4.0 on 2024-12-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MabatiApp', '0007_product_created_at_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
